-- 数据库模式建表脚本
-- 这个脚本包含 Document、User、ChatHistory 三张表，按照项目实体类设计

CREATE DATABASE IF NOT EXISTS ai_document_agent CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
USE ai_document_agent;

CREATE TABLE IF NOT EXISTS document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    file_name VARCHAR(255) NOT NULL COMMENT '文件名',
    file_path VARCHAR(500) DEFAULT NULL COMMENT '文件存储路径',
    file_type VARCHAR(100) DEFAULT NULL COMMENT '文件类型',
    file_size BIGINT DEFAULT 0 COMMENT '文件大小',
    content TEXT COMMENT '文档内容',
    summary VARCHAR(500) DEFAULT NULL COMMENT '文档摘要',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档存储表';

CREATE TABLE IF NOT EXISTS `user` (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    username VARCHAR(150) NOT NULL COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT DEFAULT NULL COMMENT '用户ID',
    doc_id BIGINT DEFAULT NULL COMMENT '关联文档ID',
    question TEXT COMMENT '用户问题',
    answer TEXT COMMENT 'AI回答',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聊天历史表';