# 服务端口（和Python 8080区分开）
server:
  port: 8083

# 文件上传配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  # MySQL数据库配置（对应你的Document/User/ChatHistory实体）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  #jdbc是java的数据库驱动，用于连接mysql数据库
    url: jdbc:mysql://localhost:3306/ai_document_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms

# Python AI服务配置（必须和你FastAPI启动的地址一致）
python:
  service:
    base-url: http://127.0.0.1:8080

# MyBatis-Plus配置
mybatis-plus:
  #mapper-locations: classpath:mapper/*.xml     让mybatis去mapper文件夹下找xml写的SQL语句，但是我项目用的是mybatisplus，根本不用写XML SQL
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   控制台打印执行的SQL语句，项目上线时注释掉，避免占性能、泄露数据
  global-config:
    db-config:
      # 防止全表更新和删除
      block-attack-enable: true


# JWT配置
jwt:
  secret: 12345678901234567890123456789012
  expiration: 1800000
  refresh-expiration: 604800000